### ISSUE TITLE
Godaddy申请失败

### ISSUE THREAD

**Issue by Alpha-liu** [sadoneli/merlin380-acme#4]
申请时DNS服务商已经改为Dodaddy，但还是申请失败

【2018年04月11日 20:43:25】: 开始为xxx.club申请证书！
【2018年04月11日 20:43:25】: 证书申请过程可能会持续3分钟，请不要关闭或刷新本网页！
【2018年04月11日 20:43:27】: 使用GoDaddy接口申请证书...
[Wed Apr 11 12:43:35 GMT 2018] Creating domain key
[Wed Apr 11 12:43:38 GMT 2018] The domain key is here: /koolshare/acme/notation.club/xxx.club.key
[Wed Apr 11 12:43:38 GMT 2018] Multi domain='DNS:xxx.club,DNS:nas.xxx.club'
[Wed Apr 11 12:43:38 GMT 2018] Getting domain auth token for each domain
[Wed Apr 11 12:43:39 GMT 2018] Getting webroot for domain='xxx.club'
[Wed Apr 11 12:43:39 GMT 2018] Getting new-authz for domain='xxx.club'
[Wed Apr 11 12:43:46 GMT 2018] The new-authz request is ok.
[Wed Apr 11 12:43:46 GMT 2018] Getting webroot for domain='nas.xxx.club'
[Wed Apr 11 12:43:46 GMT 2018] Getting new-authz for domain='nas.xxx.club'
[Wed Apr 11 12:43:51 GMT 2018] The new-authz request is ok.
[Wed Apr 11 12:43:51 GMT 2018] Found domain api file: /jffs/.koolshare/acme/dnsapi/dns_cf.sh
[Wed Apr 11 12:43:51 GMT 2018] You didn't specify a cloudflare api key and email yet.
[Wed Apr 11 12:43:52 GMT 2018] Please create the key and try again.
[Wed Apr 11 12:43:52 GMT 2018] Error add txt for domain:_acme-challenge.xxx.club
[Wed Apr 11 12:43:52 GMT 2018] Please add '--debug' or '--log' to check more details.
[Wed Apr 11 12:43:52 GMT 2018] See: https://github.com/Neilpang/acme.sh/wiki/How-to-debug-acme.sh
【2018年04月11日 20:44:00】: 证书申请失败，请检查插件配置、域名等是否正确！！
【2018年04月11日 20:44:00】: 清理相关残留并关闭插件！！

**Comment by Alpha-liu** [comment]
问题已经查明，调用api错误。请更新acme_config.sh第49行为dns_gd

**Comment by sadoneli** [comment]
https://github.com/sadoneli/merlin380-acme/commit/23dde6fa352b18d30f4d306caea2e959283c7473

**Comment by Alpha-liu** [comment]
lol
